### ISSUE TITLE
New feature idea: Ability score analysis of a party

### ISSUE THREAD

**Issue by Kudusch** [njlyon0/dndR#5]
Love the package and would like to contribute! 

I thought it might be a fun feature to input and plot the ability scores of a given list of characters (e.g. a party) to have a better idea of how ability scores are distributed across the characters. This might look something like this:

![plot-by-ability](https://kudusch.de/projects/uploads/files/ability.png)
![plot-by-player](https://kudusch.de/projects/uploads/files/player.png)

The main function for this would be something like `party_diagram(by = "player")`, where the user either gives a list of ability scores or is guided through a simple interactive menu (after the interactive menu was used, the function should also output the representation of the ability score list that can be provided to the function). Here is an example of how this could look:
![example-usage](https://kudusch.de/projects/uploads/files/example_party_diagram.png)

I have a fork with an implementation of this here: [Kudusch/dndR@party_diagram](https://github.com/Kudusch/dndR/tree/party_diagram)
If you feel like this could be in the scope of the package and if you're interested I could to a PR!

**Comment by njlyon0** [comment]
Wow this looks really cool! Thanks for taking the time to script this out.

Please do submit a PR and I can give it a closer look.

Also, I'd love to add you as an official contributor once we get the PR merged if you are interested! If that does sound like something you'd like, can you tell me (1) first / last name, (2) a URL you'd like included as a comment (personal website, GitHub profile, etc.)

**Comment by Kudusch** [comment]
Cool! I just opened the PR. 

My name is Tim Schatto-Eckrodt and you could link to [this page](https://kudusch.de) if this works out :)

**Comment by njlyon0** [comment]
## Done!

Your function has been integrated and I added a new [page to the website](https://njlyon0.github.io/dndR-website/party_diagram.html) to demonstrate `party_diagram`. Thanks Tim!!
